language: ruby
rvm:
- 2.5.3
before_install:
- openssl aes-256-cbc -K $encrypted_d524091f0fc5_key -iv $encrypted_d524091f0fc5_iv
  -in Jack-prot-41d5a177768d.json.enc -out Jack-prot-41d5a177768d.json
  -d
deploy:
  provider: gae
  keyfile: "Jack-prot-41d5a177768d.json"
  project: "jack-prot"
  on:
    branch: release